# from page_object.临停订单查询 import Linting
#
# class Lintingdingdan(Linting):
#     def dingdan(self,input_time,input_carnumber):
#         self.click_loc(self.dingdanguanli)
#         self.click_loc(self.lintingdingdan)
#         self.click_loc(self.car_order)
#         self.click_loc(self.car_chose)
#         self.click_loc(self.time_input_click)
#         self.clear_loc(self.time_input_)
#         self.input_loc(self.time_input_,txt=input_time)
#         self.click_loc(self.button_allright)
#         self.click_loc(self.button_all)
#         self.click_loc(self.button_zhankai)
#         self.input_loc(self.car_input, txt=input_carnumber)
#         self.click_loc(self.car_quyu)
#         self.click_loc(self.chose_quyu)
#         self.click_loc(self.zhifuchangjing)
#         self.click_loc(self.chose_changhjing)
#         self.click_loc(self.zhifuleixing)
#         self.click_loc(self.chose_leixing)
#         self.click_loc(self.dingdanzhaungtai)
#         self.click_loc(self.chose_zhaungtai)
#         self.click_loc(self.kaipiaozhuangtai)
#         self.click_loc(self.chose_kaipiao)
#         self.click_loc(self.zhifuqudao)
#         self.click_loc(self.chose_qudao)
#         self.click_loc(self.zhifufenlei)
#         self.click_loc(self.chose_fenlei)
#         self.click_loc(self.button)
